### ISSUE TITLE
Is it possible to inspect objects from a list

### ISSUE THREAD

**Issue by tkdchen** [mgedmin/objgraph#45]
Hi, `show_growth` can show created lists since last call. Is it possible for objgraph to show the specific objects inside a list?

**Comment by mgedmin** [comment]
I'm not sure I understand the question?

**Comment by mgedmin** [comment]
Ah!  You'd have to use ` get_new_ids()` instead of `show_growth()` to get the information about specific objects.  The example at https://mg.pov.lt/objgraph/objgraph.html#objgraph.get_new_ids shows you how to get all the newly created list objects since previous call, and then you can inspect them using traditional tools like print() or pprint.pprint().
